spring:
  application:
    name: mylfa
  datasource:
    url: jdbc:postgresql://ru.cloud.whiteo.de:5432/mylfa
    username: dbuser
    password: Password!23
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
  flyway:
    schemas: mylfa
    table: flyway_schema_history
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: mylfa
        jdbc:
          batch_size: 1000
          order_inserts: true
          order_updates: true
          lob:
            non_contextual_creation: true
    open-in-view: false
  sql:
    init:
      platform: h2
      encoding: UTF-8
  main:
    banner-mode: off
server:
  port: 8080
  servlet:
    context-path: /mylfa
logging:
  level:
    de:
      whiteo:
        mylfa: DEBUG
jwt:
  expiration:
    time: 86400000
  secret:
    key: super_secret_key_yeah_this_key_is_amazing_1234567890!@#
app:
  version: "@project.version@"
  demo-only: false
  main-directory: "./mylfa/"
  lang-directory: "./mylfa/languages/"
  lang-repository: "https://github.com/tesseract-ocr/tessdata/raw/main/"
  lang-file-extension: ".traineddata"