spring:
  application:
    name: mylfa
  datasource:
    url: jdbc:postgresql://${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PWD}
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
  flyway:
    schemas: mylfa
    table: flyway_schema_history
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: mylfa
        jdbc:
          batch_size: 1000
          order_inserts: true
          order_updates: true
          lob:
            non_contextual_creation: true
    open-in-view: false
  sql:
    init:
      platform: h2
      encoding: UTF-8
  main:
    banner-mode: off
server:
  port: 8080
  servlet:
    context-path: /mylfa
logging:
  level:
    de:
      whiteo:
        mylfa: ${APP_LOG_LEVEL}
jwt:
  expiration:
    time: ${TOKEN_EXPIRATION_TIME}
  secret:
    key: ${TOKEN_SECRET_KEY}
app:
  version: "@project.version@"
  demo-only: ${DEMO_ONLY}
  main-directory: "./mylfa/"
  lang-directory: "./mylfa/languages/"
  lang-repository: "https://github.com/tesseract-ocr/tessdata/raw/main/"
  lang-file-extension: ".traineddata"